# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f99baad4b6f755705c6c9b433b896c3fd38f7270c2d870f16cfe509a9a90539f65518c38e155c53598b50bbf3517773c0eef3bd7103841841e01065d4df7de3d

test:
  secret_key_base: 4b1b8d5d6a766c0ad81c3273d3331cea5b697e61790072c3d0a1c53c114d0088e3eb84561cabad849280b060c24abec131e5ab066057a4a5f6f2aaff9f1b0d9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
